# Generated by Django 4.2.7 on 2024-02-05 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeId', models.IntegerField()),
                ('Type', models.CharField(max_length=50)),
                ('TutionFees', models.IntegerField()),
                ('DevelopmentFees', models.IntegerField()),
                ('OtherFees', models.IntegerField()),
                ('ExamFees', models.IntegerField()),
                ('DepositAndCautionMoney', models.IntegerField()),
                ('StudentInsurance', models.IntegerField()),
                ('AlumniAssociationLifeMembershipFees', models.IntegerField()),
                ('ConvocationFees', models.IntegerField(default=0)),
                ('Contingency', models.IntegerField(default=0)),
                ('TotalFee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=20)),
                ('TransactionId', models.CharField(max_length=50)),
                ('TransactionTypeId', models.IntegerField(default=0)),
                ('FeesTypeId', models.IntegerField(default=0)),
                ('Amount', models.IntegerField()),
                ('DateTime', models.DateTimeField(max_length=50)),
                ('Method', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Mobile', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=10)),
                ('Caste', models.CharField(max_length=20)),
                ('CasteCategory', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=50)),
                ('CourseYear', models.CharField(max_length=20)),
                ('AcademicYear', models.CharField(max_length=10)),
                ('FeesTypeId', models.IntegerField(blank=True, default=None, null=True)),
                ('TotalFees', models.IntegerField()),
                ('RemainingFees', models.IntegerField()),
                ('PaidFees', models.IntegerField()),
                ('FeesStatus', models.CharField(max_length=10)),
                ('LastLogin', models.DateTimeField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
